#服务配置
server:
  port: 9001
#spring 配置
spring:
  #应用配置
  application:
    name: artc-web
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/artc?useUnicode=true&characterEncoding=utf8
    username: root
    password: 963963963Zz
mybatis:
  mapper-locations: classpath*:org/artc/**/mapper/**/*Mapper.xml
